site_name: ArqonBus
site_url: "https://www.arqoncloud.com"
repo_url: https://github.com/novelbytelabs/arqonbus/
repo_name: arqonbus
dev_addr: 127.0.0.1:8001

theme:
  name: 'material'
  palette:
    scheme: slate
  features:
    - navigation.sections
#    - navigation.expand
#    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate

nav:
  - 'Home': 'index.md'
  - 'API Reference': 'api.md'
  - 'Design & Architecture': 'architecture.md'
  - 'Completion Report': 'completion_report.md'

markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.superfences

# Custom CSS file for additional styling
extra_css:
  - stylesheets/extra.css

# This tells mkdocs where your documentation source files are
docs_dir: 'docs'

# This allows GitHub Actions to deploy the site to the gh-pages branch
edit_uri: edit/main/docs/